hosts: all
 - name: Update APT package cache
   apt: update_cache=yes cache_valid_time=3600
 - name: Upgrade APT to the latest packages
   apt: upgrade=safe
 - name: apt install
   apt:
    pkg:
     - nano
     - zsh
     - ufw
     - unattended-upgrades 
     - apt-listchanges
     - fail2ban
     - docker
     - python3

 - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
   ansible.builtin.user:
     name: jonty
     shell: /bin/zsh
     create_home: 'true'
     password: 1234