---
- hosts: all
  tasks:
  - name: Update APT package cache
    apt: update_cache=yes cache_valid_time=3600
  - name: Upgrade APT to the latest packages
    apt: upgrade=safe
  - name: apt install
    apt:
     pkg:
      - nano
      - zsh
      - ufw
      - unattended-upgrades
      - apt-listchanges
      - fail2ban
      - docker
      - python3
  - name: install modules
    raw: ansible-galaxy collection install ansible.posix
  - name: Add the user Jonty
    ansible.builtin.user:
     name: jonty
     groups: sudo
     shell: /bin/zsh
     create_home: true
     password: '$6$HoKZKqbi$nYVvf0b2L3uTCWW3ARkeT3N0EIvNpIl9cGHwqf9eIKZ3Txmpaz4crfhI/4iqwWB6Q5NUOxQtOurMAf3G6LWdb.'
  - name: chown jonty
    raw: chown jonty /home/jonty/ 
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
     user: jonty
     state: present
     key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF3razQ7lq0fnMLPbLBaeHIvIa/elHMc1AaEGnU7NWJX jontyms@protonmail.com"
  - name: jonty tasks
    block:
     - name: install oh my zsh
       raw: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
     - name: zsh syntax
       raw: ~ git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
     - name: zsh autosuggestions
       raw: ~ git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    become: true
    become_user: jonty
...
